import { Link, createFileRoute } from "@tanstack/react-router";
import { ArrowRight, Check, Instagram, MessageCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { EnquiryForm } from "@/components/enquiry-form";

export const Route = createFileRoute("/contact")({
  head: () => ({ meta: [
    { title: "Custom Order Enquiry | thaddeus creates" }, { name: "description", content: "Prepare an enquiry for a personalised resin, paper or satin creation from thaddeus creates." },
    { property: "og:title", content: "Custom Order Enquiry | thaddeus creates" }, { property: "og:description", content: "Start shaping a thoughtful handmade gift for your person or occasion." },
    { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
  ] }), component: ContactPage,
});

function ContactPage() {
  const details = ["The occasion and who it is for", "Which creation caught your eye", "Names, dates, colours or photos to include", "When you hope to give it"];
  return <main><section className="mx-auto max-w-7xl px-5 pb-16 pt-14 sm:px-8 sm:pt-20 lg:px-12 lg:pb-24"><div className="max-w-2xl"><p className="section-kicker">Begin an enquiry</p><h1 className="mt-3 font-display text-5xl font-light leading-[0.98] sm:text-7xl">Tell us about the moment.</h1><p className="mt-6 text-lg leading-8 text-muted-foreground">Custom pieces begin with a few thoughtful details. Gather what you know now; the rest can be shaped together.</p></div><div className="mt-12 grid gap-10 lg:grid-cols-[1.15fr_0.85fr] lg:gap-16"><EnquiryForm /><div className="rounded-lg bg-secondary p-6 sm:p-10"><p className="section-kicker text-secondary-foreground/70">Helpful things to share</p><ul className="mt-6 space-y-5">{details.map((item) => <li key={item} className="flex gap-3 text-sm font-medium leading-6 text-secondary-foreground"><span className="mt-0.5 grid size-5 shrink-0 place-items-center rounded-full bg-background"><Check className="size-3" /></span>{item}</li>)}</ul><div className="mt-9 border-t border-secondary-foreground/15 pt-6"><p className="text-sm leading-6 text-secondary-foreground/75">Prefer a direct chat or quick photo share? Message us on Instagram or WhatsApp.</p><div className="mt-5 flex flex-wrap gap-3"><Button asChild variant="tactile-ink" size="lg"><a href="https://www.instagram.com/thaddeus_creates/" target="_blank" rel="noreferrer">Instagram <Instagram className="size-5" /></a></Button><Button asChild variant="outline" size="lg" className="border-secondary-foreground/30 bg-background text-foreground hover:bg-muted"><a href="https://wa.me/919654435911?text=Hi%20Thaddeus%20Creates,%20I'm%20interested%20in%20a%20custom%20keepsake" target="_blank" rel="noreferrer">WhatsApp Chat <img src="/whatsapp-svgrepo-com.svg" alt="" className="size-5 shrink-0" /></a></Button></div><Link to="/creations" className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-secondary-foreground">Explore creations <ArrowRight className="size-4" /></Link></div></div></div></section><section className="border-t border-border bg-card px-5 py-14 sm:px-8 sm:py-20 lg:px-12"><div className="mx-auto max-w-7xl"><p className="section-kicker">What happens next</p><ol className="mt-7 grid gap-7 md:grid-cols-3">{[["01", "Share the idea", "Send the occasion, piece and personal details you have in mind."], ["02", "Shape the details", "Colours, wording, photographs and finishes are aligned together."], ["03", "Made for your moment", "The agreed piece is carefully handcrafted around your choices."]].map(([n, title, copy]) => <li key={n} className="border-t border-border pt-5"><span className="text-xs font-semibold text-primary">{n}</span><h2 className="mt-4 font-display text-2xl font-medium">{title}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{copy}</p></li>)}</ol></div></section></main>;
}